### ISSUE TITLE
Problems on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [khenriks/mp3fs#37]
NetBSD provides a FUSE implementation. However, I can't get mp3fs-0.91 to work with it (0.13 worked fine).

The problems I have seen so far:
- command line argument parsing does not work correctly: "-b 128", "--bitrate=128" are not recognized; "-h", "-V" cause core dumps.
- "mp3fs /foo /bar" errors out instead of mounting /a to /b

I don't know yet if this is a problem in the NetBSD FUSE implementation or mp3fs; however, many other fuse file systems work fine (including e.g. glusterfs).

**Comment by khenriks** [comment]
I don't have access to a NetBSD system, and haven't had time to get one set up in order to test this. I'll just comment instead that NetBSD is not a supported platform. I have no idea why it would crash so easily, and otherwise not function. It's probably some incompatibility between the NetBSD and Linux FUSE implementations. Sorry I'm not more helpful, I really have no idea, and no experience with NetBSD.
