### ISSUE TITLE
cannot add mp3fs to fstab

### ISSUE THREAD

**Issue by xedni** [khenriks/mp3fs#41]
When I try to add the entry to fstab (i.e. mp3fs#/mnt/music /mnt/mp3 fuse allow_other,ro,bitrate=192 0 0), it becomes impossible to log in as usual. Instead, the system goes into emergency mode (i.e. terminal and no GUI).

**Comment by khenriks** [comment]
Are there any messages in the system log or boot log to indicate what's wrong? What operating system are you using? What happens if you put it in fstab and use the mount command instead of rebooting to mount the directory?

**Comment by xedni** [comment]
I'm much too much of a noob to know what to look for in the log,
    unfortunately. If you gave me some pointers I'd gladly have a look.
    I'm using Debian stable. Could you indicate as to how to use the
    mount command in this instance please?
    On 07/03/15 04:05, K Henriksson wrote:
    
    
      Are there any messages in the system log or boot log to
        indicate what's wrong? What operating system are you using? What
        happens if you put it in fstab and use the mount command instead
        of rebooting to mount the directory?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      
      
      In response
          to a [privacy] lawsuit filed in May 2013, Google explained: 
        
      "... all users of email must
          necessarily expect that their emails will be subject to
          automated processing ... Just as a sender of a letter to a
          business colleague cannot be surprised that the recipient's
          assistant opens the letter, people who use web-based email
          today cannot be surprised if their communications are
          processed by the recipient's ECS [electronic communications
          service] provider in the course of delivery".

**Comment by khenriks** [comment]
To try using the mount command in this instance, you would use `sudo mount /mnt/mp3` as long as the entry is in the fstab file. To check the system log, have a look at /var/log/syslog after the failure and look for any messages that came from mp3fs or that look related.

**Comment by exptom** [comment]
I had the same problem on Debian Jessie until I manually installed the fuse package.

```
sudo aptitude install fuse
```

**Comment by sarnold** [comment]
That sounds like a missing package dependency; it should absolutely have a runtime dependency on fuse (both userspace tools and kernel modules/config).  If you add the "noauto" mount flag you should be able to boot fine, then you can manually mount when you need to.  it also needs a couple of other flags for user-mount and proper config, so this is what I use:

```
mp3fs#/path/to/flac   /home/mp3   fuse   bitrate=192,ro,user,allow_other,noauto 0 0
```

**Comment by shaleh** [comment]
The Debian package does not depend on fuse like it should. This is a Debian bug and should be reported there.

Fellow Debian users, do not post bugs upstream. Send your bugs to Debian and let them follow the issue. Many, many times the bugs are due to minor changes in Debian and not the upstream's fault. Even when it is a legitimate upstream bug having the Debian maintainers involved usually makes the process work better.

**Comment by bvrulez** [comment]
Hello and thank you very much for this awesomeness! I used manual mount until now but also wanted to put mp3fs into my fstab. Unfortunately, it does not work. I am able to mount my directory mp3fsben, but `ls mp3fsben` then just gives a blinking cursor and no progress. My entry in fstab is 

`mp3fs#/home/ben/.benshare/OMV/Musik/music /home/ben/.benshare/mp3ben fuse noauto,user,allow_other,ro,bitrate=256 0 0`,

where /OMV is a mountpoint of a share. But that should not be a problem, since this mount works well.

**Comment by khenriks** [comment]
Are you missing the `fuse` package, as was suggested above?

**Comment by bvrulez** [comment]
I am not really sure any more why this came up. Chances are my problem was that the connection to the share was slow. I changed the mount point so that now mp3fs runs on the server and not on the client. I now access the samba on the share via the client and then inside this folder there is a mp3fs directory on the share already - instead of having a dedicated mp3fs directory on the client. I really thank you for this genius implementation! This makes things so much easier!

**Comment by khenriks** [comment]
You're welcome! Glad to hear you found a way to make it work.
