### ISSUE TITLE
QNAP package for v1.0

### ISSUE THREAD

**Issue by the-nicolas** [khenriks/mp3fs#64]
Where can I find the installation packages for v1.0?

I just found v0.9 from 2017 and I get random segfaults when sharing fuse folder via network.
Looks like some multi-threaded bugs got fixed recently, perhaps that would fix the problem...

Thanks!

**Comment by RobMeerwijk** [comment]
You could try to install docker on your QNAP. And then it is easy to install the mp3fs docker container. Works like a breeze. https://registry.hub.docker.com/r/khenriks/mp3fs

On my Synology I had to execute `sudo mount --make-shared /volume1` in order to make the mp3 fuse filesystem available outside docker (source https://github.com/madslundt/docker-cloud-media-scripts/issues/35 )

**Comment by khenriks** [comment]
I don't know anything about QNAP or the packages on there, sorry. I don't have anything to do with them.

I recommend trying docker as @RobMeerwijk mentions though, since that is released by me and works anywhere that docker runs.
