### ISSUE TITLE
Sometimes fails when used with rsync

### ISSUE THREAD

**Issue by viertelb** [khenriks/mp3fs#67]
Thanks again for the great tool! 

I am not sure if this error is due to my personal setup which involves samba shares and potentionally slow connections or harddisks. But when I use `rsync` I often get this error:

`rsync: read errors mapping "my mp3 file": No data available (61)`

I then use `cp` to copy those files without a problem. 

It might be related to me tagging them files with `easytag` before. It seems it occurs more on "recent" files than on older ones. Unfortunately, I cannot provide more information. I will have an eye on it. Just posting this to see if anyone else has this issue.

EDIT: The file is read to 100%, but then the verification fails. Not sure if this is related to mp3fs or to the target file system.

**Comment by khenriks** [comment]
Can you provide the output of `mp3fs --version` and also provide the flags you're using to mount with?

**Comment by bvrulez** [comment]
```
benraid@OMV:/srv$ mp3fs --version
mp3fs git version: v0.91-96-g34cb13b
LAME library version: 3.99.5
FLAC library version: 1.3.2
Xiph.Org libVorbis 1.3.5
FUSE library version: 2.9

```

Just realized this is a very old version. I am running Openmediavault

`Linux OMV 4.19.0-0.bpo.9-amd64 #1 SMP Debian 4.19.118-2+deb10u1~bpo9+1 (2020-06-09) x86_64 GNU/Linux`

and upgraded via git to

```
mp3fs git version: v1.1.1-1-g68b7193
```

I hat to use `sudo apt install` because `aptitude` is not working on my system - despite beeing Debian based (your installation guide refers just to `aptitude`).

My mount works via command line and hast options `-o allow_other,ro'`.

Next time I do a large sync I will have a look it the problem persists.

**Comment by khenriks** [comment]
Ok, please take a look and let me know. There were quite a few fixes since your version that could have affected this.

Thanks for mentioning the issue with `aptitude` vs. `apt`. I should update that documentation.

**Comment by viertelb** [comment]
> Ok, please take a look and let me know. There were quite a few fixes since your version that could have affected this.

I am in the process of `rsync`ing and after 90GB the problem did not come up once. I am pretty sure the newer versions don't have this bug any more. Thanks a lot!
